# Make sure to check the documentation at https://goreleaser.com
version: 2
project_name: wg-manager
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - riscv64
    main: ./cmd/wg-manager
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

archives:
  - name_template: >-
      {{ .ProjectName }}-
      {{- .Os }}-
      {{- .Arch  }}
    builds_info:
      group: root
      owner: root
    files:
      - README.md
      - LICENSE

release:
  mode: replace
  draft: false
  prerelease: auto

  github:
    owner: ernado
    name: wg-manager

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: 'Helm chart updates'
      order: 700
      regexp: '^.*?(feat|fix|chore)\(helm\)!?:.+$'
    - title: 'Dependency updates'
      regexp: '^.*?(feat|fix|chore)\(deps\)!?:.+$'
      order: 300
    - title: 'New Features'
      regexp: '^.*?feat(\(\S+\))??!?:.+$'
      order: 100
    - title: 'Security updates'
      regexp: '^.*?sec(\(\S+\))??!?:.+$'
      order: 150
    - title: 'Performance updates'
      regexp: '^.*?perf(\(\S+\))??!?:.+$'
      order: 250
    - title: 'Bug fixes'
      regexp: '^.*?fix(\(\S+\))??!?:.+$'
      order: 200
    - title: 'Documentation updates'
      regexp: '^.*?docs(\(\S+\))??!?:.+$'
      order: 400
    - title: 'Benchmarking tooling changes'
      regexp: '^.*?(\(\S*bench\S*\))!?:.+$'
      order: 450
    - title: 'Build process updates'
      regexp: '^.*?build(\(\S+\))??!?:.+$'
      order: 500
    - title: 'CI/CD updates'
      regexp: '^.*?ci(\(\S+\))??!?:.+$'
      order: 600
    - title: 'Updates to tests'
      regexp: '^.*?test(\(\S+\))??!?:.+$'
      order: 600

    - title: Other work
      order: 9999

sboms:
  - artifacts: archive

nfpms:
  - package_name: wg-manager
    homepage: https://github.com/ernado/wg-manager
    maintainer: Aleksandr Razumov <ernado@go-faster.org>
    description: WireGuard manager.
    license: Apache 2.0
    formats:
      - apk
      - deb
      - rpm
      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
    bindir: /usr/bin
    contents:
      - src: ./_systemd/wg-manager.service
        dst: /etc/systemd/system/wg-manager.service
        type: config
